.github/.styles/Google/WordList.yml
.github/.styles/config/vocabularies/Webforj/accept.txt
docs/data-binding/_category_.json
docs/data-binding/_validation.md
docs/data-binding/automatic-binding.md
docs/data-binding/bindings.md
docs/data-binding/overview.md
docs/data-binding/transformation.md
docs/data-binding/validation/_category_.json
docs/data-binding/validation/context-results.md
docs/data-binding/validation/jakarta-validation.md
docs/data-binding/validation/overview.md
docs/data-binding/validation/reporters.md
docs/data-binding/validation/triggers.md
docs/data-binding/validation/validators.md
src/css/custom.css

@MatthewHawkins Please review the language used and correct any easily fixable issues.

feat: add data-binding documentations

---

docs/components/_dwc_control_map.json
docs/components/login.md

@MatthewHawkins Please review the language used and correct any easily fixable issues.

feat: add login documentations

---

.github/.styles/config/vocabularies/Webforj/accept.txt
docs/components/option-dialogs/_category_.json
docs/components/option-dialogs/configm.md
docs/components/option-dialogs/confirm.md
docs/components/option-dialogs/file-chooser.md
docs/components/option-dialogs/file-upload.md
docs/components/option-dialogs/input.md
docs/components/option-dialogs/message.md
docs/components/option-dialogs/option-dialogs.md

depends on : https://github.com/webforj/webforj-docs-samples/pull/34 and https://github.com/webforj/webforj/pull/584
@MatthewHawkins Please review the language used and correct any easily fixable issues.

docs: add Option dialog docs

---

docs/components/progressbar.md

@MatthewHawkins Please review the language used and correct any easily fixable issues.

docs: Add ProgressBar component documentation

---

docs/components/fields/number-field.md
docs/components/fields/text-field.md
docs/components/list-components/lists.md

Additonally fixed hyperlinks on the Lists page.

Corrected NumberField and TextFiled important tags descriptions.

---

docs/data-binding/home.md
docs/data-binding/validation/triggers.md
docs/styling/getting_started.md

Pull request to resolve issue 174.

174 size api

---

blog/2024-07-23-webforj-v24.10/24.10.md
docs/components/splitter.md
docs/getting_started/configuration.md
docs/getting_started/creating_an_application.md
docs/ui/element-composite.md

I've made some edits across some pages where I noticed grammatical errors, focusing on pages with higher visibility.
There are only a couple strictly necessary fixes; otherwise I focused on improving clarity and conforming to our style guidelines.

202 grammatical errors

---

docs/components/list-components/lists.md

Removed indention on tip block.

Formatted Tip

---

docs/components/charts/google_charts.md
docs/components/google_charts.md

New Google Charts documentation

88 document googlecharts

---

docs/components/button.md
docs/components/list-components/choice-box.md
docs/components/list-components/combo-box.md

Fixes #63 https://github.com/webforj/webforj-docs/issues/63
Fixes #53 Remove first list item in ChoiceBox > Usages > User Selection of Options
Some grammatical/style fixes as well.

Easy fixes for a couple issues

---

docs/components/columns-layout.md

PR for grammar corrections on https://documentation.webforj.com/docs/components/columns-layout
This PR closes Issue #245.

PR: Grammar and typo corrections for columns-layout.md

---

docs/components/flex_layouts.md

Pull Request - Added tip about ColumnsLayout in Example Form section

---

docs/advanced/terminate-and-error-actions.md

feat: add documentation for terminate and error actions in webforJ

---

docs/advanced/error-handling.md
docs/advanced/terminate-and-error-actions.md

feat: add documentation for error handling in webforJ

---

docs/components/lists/choice-box.md
docs/components/lists/combo-box.md
src/css/custom.css

- Added a section to the ComboBox and ChoiceBox pages talking about the prefix and suffix slots
-This PR closes #225.

PR Added Slot section to ComboBox and ChoiceBox

---

docs/building-ui/elements.md
docs/components/button.md
docs/components/checkbox.md
docs/components/dialog.md
docs/components/drawer.md
docs/components/fields/color-field.md
docs/components/fields/date-field.md
docs/components/fields/date-time-field.md
docs/components/fields/number-field.md
docs/components/fields/password-field.md
docs/components/fields/text-field.md
docs/components/fields/time-field.md
docs/components/flex_layouts.md
docs/components/lists/choice-box.md
docs/components/lists/combo-box.md
docs/components/lists/list-box.md
docs/components/login.md
docs/components/option-dialogs/confirm.md
docs/components/option-dialogs/file-chooser.md
docs/components/option-dialogs/file-upload.md
docs/components/option-dialogs/input.md
docs/components/option-dialogs/message.md
docs/components/radio-button.md
docs/components/radio-group.md
docs/components/spinner/spinner.md
docs/components/splitter.md
docs/components/tabbed-pane.md
docs/components/table/table_columns.md

In cases where it seemed useful, I left the demos to exist at the bottom of the overview section. Also did a little bit of minor tidying up of grammar and layout.
Closes #158

Removed constructor sections for all component pages.

---

docs/components/fields/fields.md

This closes #224.
The description in this section is from PR https://github.com/webforj/webforj-docs/pull/253.

PR Added Slots section under Shared Field Properties

---

docs/components/drawer.md

This PR closes #268.
This PR changes a single URL of the first sample on the Drawer article.

PR Rerouted AppLayoutViewer URL

---

.github/CODEOWNERS
docs/components/lists/choice-box.md
docs/components/lists/combo-box.md

This PR closes #67 .
The Opening and Closing sections, added under Max Row Count, also briefly mention that event listeners are available for these actions.

PR - Added Opening and Closing section for ComboBox and ChoiceBox

---

docs/components/button.md

This PR closes #221.
Updated this section of the Button article to include the mention of the `Icon` component.
There are several other PRs that should be approved before this one is merged:
- PR #283
- PR #282
- From webforj-doc-samples: [PR #89](https://github.com/webforj/webforj-docs-samples/pull/89) Removal of html tags and dwc-icons.

PR: Updated "Adding icons to buttons" section

---

docs/components/_dwc_control_map.json
docs/components/toast.md

Updated the Toast doc, links, etc.
closes #180

PR - Updated Toast Doc

---

docs/components/flex-layout.md

This PR closes #294.
Included the FlexLayout Flex Basis sample from webforj-docs-samples [PR #94](https://github.com/webforj/webforj-docs-samples/pull/94).

PR: Added FlexLayout Basis sample

---

docs/components/drawer.md

PR: Add Drawer DocChips

---

docs/getting-started/configuration.md

PR: Rewrote configuration to emphasis singular `App` class usage

---

docs/components/app-layout.md

PR: Added DocChips to AppLayout article

---

blog/2024-04-08-webforj-v24.00/24.00.md
docs/advanced/web-storage.md
docs/architecture/architecture.md
docs/components/table/table_rendering.md
docs/introduction/getting-started.md

This PR closes Issue #324.
Corrected cases of "webforj" in the text to "webforJ".

PR: Corrected Capitalization of "webforj" to "webforJ"

---

docs/components/icon.md

docs: Grammar Corrections for `Icon` Article

---

blog/2024-07-23-webforj-v24.10/24.10.md

chore: Changed URL for Toast Demo on 24.10.md

---

docs/components/button.md

chore: Corrected `cssURL` Values in Button Article

---

blog/2024-07-23-webforj-v24.10/24.10.md
docs/building-ui/composite-components.md
docs/building-ui/elements.md
docs/components/columns-layout.md
docs/components/flex-layout.md
docs/components/google-charts.md
docs/components/lists/choice-box.md
docs/components/lists/combo-box.md
docs/components/splitter.md
docs/components/table/table_rendering.md
docs/components/toast.md

This PR closes Issue #399.
For `ChoiceboxMaxRowView` and `ComboBoxMaxRowView`, I've allowed room for up to 10 choices to be shown in the iframe.

chore: Corrected Demo URLs and Adjusted Heights

---

docs/building-ui/component-basics.md

chore: Pascal Case When Mentioning `WebforjException`

---

docs/components/fields/number-field.md

chore: Added a Title to a `Numberfield` Tip

---

docs/components/fields/password-field.md

chore: Rewrote `Passwordfield` Component Overview

---

docs/introduction/getting-started.md
docusaurus.config.js
src/theme/MDXComponents.js

chore: Added tab for archetype command in PowerShell
